Future-House/aviary

- README.md
More clarifications after reading the table from https://github.com/Future-House/aviary/pull/93 in the morning
> Updated messages explanatory table

- src/aviary/core.py
> aviary.core.EnvStateMessage

- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
- packages/hotpotqa/tests/test_hotpotqa_env.py
#102 accidentally set eval mode in the state, not config. This fixes that & extends tests
> Fix eval mode setting in config

- packages/gsm8k/src/aviary/envs/gsm8k/env.py
- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
- packages/hotpotqa/tests/test_hotpotqa_env.py
Unifies the name of the tool used to submit the answer in GSM8K and HotPotQA. This will potentially allow to define an Agent that simulates no-tools.
> Unify answer tool naming

- .github/workflows/tests.yml
- pyproject.toml
- uv.lock
Adding support for Python 3.13 in local dev and package classifiers
> Python 3.13 support

- packages/gsm8k/src/aviary/envs/gsm8k/env.py
- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
- src/aviary/env.py
> Replacing `list[Messages]` with `Messages` in environments

- packages/gsm8k/src/aviary/envs/gsm8k/env.py
- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
- pyproject.toml
- src/aviary/env.py
- src/aviary/render.py
- src/aviary/tools/argref.py
- src/aviary/tools/server.py
- tests/test_envs.py
Made it easier for `Env` to offload invalid tool handling to baseclass.
> Added invalid tool checker

- src/aviary/dataset_server.py
> Making uvicorn import lazy

- src/aviary/env.py
> Type hinted `maybe_wait_for` return

- .github/workflows/codeflash.yml
clean the yaml a bit and remove unnecessary sections
> Clean codeflash.yml config

- LICENSE
> Populated `LICENSE`

- README.md
changed 
`from aviary import fenv `
to
`from aviary.core import fenv `
in readme
> Import as written in readme for functional doesn't work

- .github/renovate.json5
> Renovate `lockFileMaintenance` respecting `schedule` and 2-week stability period

- src/aviary/utils.py
- tests/test_utils.py
> `eval_answer` allowing for `str | EvalAnswerMode` not just `EvalAnswerMode`

- packages/gsm8k/src/aviary/envs/gsm8k/env.py
- Standardized `self.tools` population to within `reset` and removed extra tools attributes
- Added `exc` to the failure message on `calculator`
- Improved the docstring by removing type hint duplication and fixing returns message
> Cleaning up GSM8k's `CalculatorEnv` a bit

- tests/test_envs.py
I wanted to confirm you can do something like:
```python
from aviary.core import Frame
frames: list[Frame]
Frame() in frames
```
> Testing `in` check with `Frame`

- CITATION.cff
Here is the BibTeX:
```none
@article{Narayanan_Aviary_training_language_2024,
author = {Narayanan, Siddharth and Braza, James D. and Griffiths, Ryan-Rhys and Ponnapati, Manvitha and Bou, Albert and Laurent, Jon and Kabeli, Ori and Wellawatte, Geemi and Cox, Sam and Rodriques, Samuel G. and White, Andrew D.},
doi = {10.48550/arXiv.2412.21154},
journal = {preprint},
month = dec,
title = {{Aviary: training language agents on challenging scientific tasks}},
url = {https://arxiv.org/abs/2412.21154},
year = {2024}
}
```
> Added a `CITATION.cff`

- src/aviary/utils.py
- tests/test_utils.py
Turns out there was more to be done here
> `RandomAnnotation` support for `model_dump(mode="json")`

- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
- packages/hotpotqa/tests/test_hotpotqa_env.py
I wanted to preserve a bit more information from the HotPotQA splits on Hugging Face
> Added question ID to `HotPotQAEnv`

- src/aviary/tools/server.py
https://github.com/Future-House/aviary/pull/188 missed updating a place where `parameters` could be `None`
> Fixed latent `NoneType` error in tool server after #188

- packages/lfrqa/src/aviary/envs/lfrqa/env.py
- packages/lfrqa/src/aviary/envs/lfrqa/task.py
Also not redefining `_query` in `LFRQAPairwiseEvalEnv.__init__`
> Not clobbering `Docs` in `LFRQAPairwiseEvalEnv`

- packages/lfrqa/src/aviary/envs/lfrqa/env.py
related issue: https://github.com/Future-House/aviary/issues/222
> fix: KeyError: 'unsure' with LFRQAPairwiseEvalEnv

- packages/gsm8k/pyproject.toml
- packages/hotpotqa/pyproject.toml
- packages/lfrqa/pyproject.toml
- packages/litqa/pyproject.toml
- pyproject.toml
> Added missing PyPI classifiers

- src/aviary/env.py
- tests/test_envs.py
> Fixed missing `None` unions in `Frame` serialization code

- packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
Turns out these aren't run by our CI as they fail, so YAGNI on totally fixing them
> Partially fixed doctests in `HotPotQAEnv`

- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- packages/gsm8k/README.md
- packages/lfrqa/README.md
- packages/litqa/README.md
- pyproject.toml
Sister PR to https://github.com/Future-House/ldp/pull/303
> Rolling out `markdownlint-cli` to lint Markdown

- .github/workflows/tests.yml
Working around https://github.com/hynek/build-and-inspect-python-package/issues/174
> Fixed `uv==0.8.0`+ BAIPP breaking `lint` CI

- packages/lfrqa/src/aviary/envs/lfrqa/env.py
- packages/lfrqa/tests/test_lfrqa_env.py
> Fixed LFRQA not being in available envs

- src/aviary/message.py
Mainly I wanted it to include the text "multimodal message" so LLM agents can benefit from this.
> Improved multimodal message docs

- packages/lfrqa/src/aviary/envs/lfrqa/env.py
- src/aviary/utils.py
> Exposing LLM configuration in `MultipleChoiceQuestion.grade`

- src/aviary/env.py
Without this, it's impossible to root cause some failures
> Env var to log `exec_tool_calls` exceptions with traceback at error level

- .github/workflows/publish.yml
> Add publish step for aviary.notebook

- src/aviary/message.py
> Removing `__future__ import annotations` from `message.py`

- src/aviary/env_client.py
A lot of our downstream code assumes that tool calls don't need error handling - it is typically handled inside the environment. `EnvironmentClient`s didn't respect this, especially in cases of timeouts. Adding an opt-in feature to do so.
> Catch EnvironmentClient errors

- packages/litqa/src/aviary/envs/litqa/task.py
- packages/litqa/tests/test_litqa_env.py
This makes trajectories easier to trace/analyze post-hoc
> LitQA matching session ID with question ID
