Future-House/aviary

.github/workflows/tests.yml
uv.lock

This PR removes the `large-runner` in favor of `ubuntu-latest` because:
- We don't need the `large-runner` in aviary, CI is lightweight
- `large-runner` is a FutureHouse internal runner, and now this repo is open source
Also, I ran `uv lock` for `uv` changing from `[package.metadata.dependency-groups]` to `[package.metadata.requires-dev]`

Moving from `large-runner` to `ubuntu-latest` for CI

---

packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
packages/hotpotqa/tests/test_hotpotqa_env.py
src/aviary/core.py
src/aviary/tools/__init__.py

- Adding a configurable EvalAnswerMode
- Setting default to CONTAINS (previous behavior was equivalent to EXACT)

Add EvalAnswerMode to HotPotQAEnv

---

.github/workflows/codeflash.yml
.pre-commit-config.yaml
pyproject.toml
uv.lock

Now that `uv` supports dependency groups, let's use em!

Moving to `uv` dependency groups

---

pyproject.toml
uv.lock

https://github.com/Future-House/aviary/pull/16 removed `SQLAlchemy`, but missed removing it from the `dev` dependencies

Removed unused `SQLAlchemy` dev dependency

---

packages/hotpotqa/src/aviary/envs/hotpotqa/env.py

"Could not find" leaves you wondering why. "returned no results" is much more explicit

HotPotQA better `search` tool failure message

---

.github/workflows/tests.yml

From [this CI run](https://github.com/Future-House/aviary/actions/runs/11737578015/job/32698600441), we get:
```none
× No solution found when resolving dependencies for split
│ (python_full_version == '3.11.*' and platform_python_implementation ==
│ 'PyPy'):
╰─▶ Because only the following versions of paper-qa are available:
paper-qa<=5.0.0
paper-qa==5.0.1
...
paper-qa==5.3.2
and paper-qa==5.3.2 depends on fhaviary, we can conclude that
paper-qa>5.3.1 depends on fhaviary.
And because paper-qa>=5.0.0,<=5.3.1 depends on fhaviary, we can conclude
that paper-qa>=5.0.0 depends on fhaviary.
And because fhaviary[paperqa] depends on paper-qa>=5 and your workspace
requires fhaviary[paperqa], we can conclude that your workspace's
requirements are unsatisfiable.
hint: The package `paper-qa` depends …
```

Adding `fetch-depth` to `actions/checkout` to fix CI

---

src/aviary/env.py

https://github.com/Future-House/aviary/pull/115 forgot sorting of the `not ordered` case

Fixing sorting of `not ordered` tool calls

---

src/aviary/env.py
tests/test_envs.py

This PR:
- Renames `ordered` to `concurrency` to dispel confusion from https://github.com/Future-House/aviary/pull/122#issuecomment-2475229576
- Writes a test as requested in https://github.com/Future-House/aviary/pull/122#pullrequestreview-2434763096

Renamed `Environment.exec_tool_calls` `ordered` to `concurrency`

---

pyproject.toml

This fixes an error we see when locally running `mypy -p aviary`:
```none
src/aviary/tools/server.py:35:1: error: Skipping analyzing "cloudpickle": module is installed, but missing library stubs or py.typed marker  [import-untyped]
import cloudpickle as pickle
^
src/aviary/tools/server.py:35:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

`mypy` ignoring `cloudpickle` as it's untyped

---

packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
src/aviary/env.py

#123 removed the `ordered` flag, but not all downstream environments have been updated. To deal with this, I am bringing the flag back and throwing a warning. We can properly deprecate it once everything has been updated.
I'm also fixing HotPotQA here for good measure.

Handling `ordered` deprecation

---

.pre-commit-config.yaml
README.md
pyproject.toml
src/aviary/core.py
src/aviary/functional.py
tests/test_functional.py
uv.lock

Per discussion on slack, new interface for defining environments:
The easiest way to create an environment is using the functional interface, which just uses functions and decorators to define environments. First, let's define what the environment looks like by defining its `start` function:
```py
from aviary import fenv
@fenv.start()
def my_env(topic):
return f"Write a story about {topic}", {"topic": topic}
```
Note that the decorator is a call (`start()`). The `start` decorator starts the definition of an environment. The function, `my_env`, can take whatever you would like and should return a tuple containing the first observation and anything you would like to store about the state of the environment (used to persist/share things between tools). The state will always automatically …

Implements new functional syntax

---

pyproject.toml
uv.lock

Failing `formatter-cmds` was leading to `codeflash` failing. This PR fixes the `formatter-cmds` integration

Fixed `codeflash`'s `formatter-cmds`

---

src/aviary/tools/base.py
tests/test_tools.py

We've been waiting a long time for it!

Added complex types to str

---

packages/hotpotqa/tests/test_hotpotqa_env.py
src/aviary/core.py
src/aviary/tools/__init__.py
src/aviary/tools/utils.py
src/aviary/utils.py

This PR closes #53 .
I moved `eval_answer` from `tools.utils` to `aviary.utils`. 
It can be imported through `aviary.core`.

Moved eval_answer from tools to core

---

src/aviary/utils.py
tests/cassettes/TestLitQAEvaluation.test_grade[didnt-match-and-llm-has-innate-knowledge].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[didnt-match-and-no-llm-innate-knowledge].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer1].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer2].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer3].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-correct-option].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-incorrect-option].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-several-options].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-unsure-option].yaml
tests/cassettes/test_eval_answer[llm basic].yaml
tests/test_utils.py

This PR generalizes https://github.com/Future-House/paper-qa/blob/a630d922d76551e9cd0258c62e2012cd5d459937/paperqa/litqa.py by creating a common multiple choice class that other environments besides `paper-qa` can use. It also aims to:
- Improves QA capability to support
- Serialization/deserialization
- Exposing attributes for ideal answer, unsure answer, distractors
- Resolves https://github.com/Future-House/paper-qa/issues/761

Created `MultipleChoiceQuestion` and `MultipleChoiceEvaluation`

---

src/aviary/core.py
src/aviary/utils.py
tests/cassettes/TestLitQAEvaluation.test_grade[didnt-match-and-llm-has-innate-knowledge].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[didnt-match-and-no-llm-innate-knowledge].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer1].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer2].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[empty-answer3].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-correct-option].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-incorrect-option].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-several-options].yaml
tests/cassettes/TestLitQAEvaluation.test_grade[matched-unsure-option].yaml
tests/cassettes/test_eval_answer[llm basic].yaml
tests/cassettes/test_eval_llm_config.yaml
tests/cassettes/test_extract_answer[complex].yaml
tests/cassettes/test_extract_answer[empty-proposal].yaml
tests/cassettes/test_extract_answer[gave-two].yaml
tests/cassettes/test_extract_answer[not in options].yaml
tests/test_utils.py

I incorporated https://github.com/Future-House/aviary/pull/148's evaluation scheme into https://github.com/Future-House/aviary/pull/157. @whitead 's prompting scheme was much better, so now we can move back to `gpt-4o-mini` for evaluation.

Moved to `extract_answer` from #148 and back to `gpt-4o-mini`

---

.pre-commit-config.yaml
packages/hotpotqa/tests/test_hotpotqa_env.py
pyproject.toml
src/aviary/tools/base.py
src/aviary/tools/server.py
tests/test_envs.py
tests/test_functional.py
tests/test_tools.py
uv.lock

This is a stand-in for Renovate doing this, because Renovate isn't working right now
While I was at it, I also fixed some test warnings about bad `async` logic:
```none
/home/runner/work/aviary/aviary/.venv/lib/python3.12/site-packages/_pytest/python.py:148: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
You need to install a suitable plugin for your async framework, for example:
- anyio
- pytest-asyncio
- pytest-tornasync
- pytest-trio
- pytest-twisted
```
```none
packages/hotpotqa/tests/test_hotpotqa_env.py::test_tool_results
/usr/lib/python3.12/asyncio/events.py:88: RuntimeWarning: coroutine 'HotPotQAEnv.submit_answer' was never awaited
```

Latest tooling and fixed some test warnings

---

src/aviary/utils.py

Pydantic silently suppressing unexpected arguments is dangerous when combined with YAML configurations (no chance of mypy catching a typo) and defaults. This is the one case in aviary where we didn't already have `extra="forbid"`.

Forbid extra arguments in configuration

---

src/aviary/core.py
src/aviary/utils.py
tests/test_utils.py

This allows one to use `MultipleChoiceQuestion` without the options being printed in the prompt. This change allows for grading, with the original agent prompt not containing options.

Allowing open answer prompting with `MultipleChoiceQuestion`

---

.pre-commit-config.yaml
pyproject.toml
src/aviary/utils.py
tests/test_utils.py
uv.lock

@ludomitch and I realized that if you specify the same `int` seed for an entire `TaskDataset` (which we don't currently do, but _could_ do), assuming the multiple choice options are the same length, the ideal answer would show up in the same index.
This PR:
1. Documents this risk
2. Adds support for `random.Random` to `MultipleChoiceQuestion`
3. Adds a (not in-place) `shuffle` utility

Allowing `random.Random` seed and documenting `TaskDataset` shuffling risk

---

pyproject.toml
src/aviary/utils.py
tests/test_utils.py

https://github.com/Future-House/aviary/pull/177 added `random.Random` support, but also added `arbitrary_types_allowed=True` to `MultipleChoiceQuestion`. I didn't like that `arbitrary_types_allowed`, so I tapped into Pydantic v2's [custom validator/serializer logic](https://docs.pydantic.dev/latest/concepts/types/#customizing-validation-with-__get_pydantic_core_schema__) to allow serialization of `random.Random`.

Removed `arbitrary_types_allowed=True` from `MultipleChoiceQuestion` via custom Pydantic serializer/validator

---

src/aviary/env.py
tests/test_envs.py

Without this, we can have failures masked in our unit testing

Moved `DummyEnv` to report empty `ToolRequestMessage`

---

src/aviary/utils.py
tests/test_utils.py

In the DataAnalysisEnv we ask the agent to solve multiple MCQs at the same time so it's useful for each MCQ to have a unique id (eg Q1, Q2, Q3 etc)

Add question_id functionality to mcq object

---

pyproject.toml
src/aviary/utils.py
uv.lock

We have a `str | None` vs `str` latent type error that was blowing up our code (calling `.strip()` on `None`), which only showed up due to https://github.com/BerriAI/litellm/issues/8507.
`mypy` should have detected this, but it didn't for some reason. Regardless, let's solve that problem later.

Allowing latest LiteLLM by handling latent `None` content error

---

pyproject.toml
src/aviary/env.py
src/aviary/tools/base.py
tests/cassettes/TestParallelism.test_dummyenv_using_empty_params.yaml
tests/conftest.py
tests/test_envs.py
tests/test_tools.py

Per https://github.com/BerriAI/litellm/issues/7634, Google `gemini-1.5-flash` can't call tools with empty `FunctionInfo.parameters.properties`. This PR adds a workaround where you manually clear out parameters with empty properties.

Allowing null `FunctionInfo.parameters` to support `gemini-1.5-flash` agents

---

.github/workflows/tests.yml

This prevents the printed failure by `pre-commit`'s `--show-diff-on-failure` showing the `.python-version` file changes.

`git checkout` before `pre-commit`

---

packages/litqa/README.md

Looks like https://github.com/Future-House/aviary/pull/190 had a bad import.
Closes https://github.com/Future-House/aviary/issues/202

Fixed `README` imports for LitQA `TASK_DATASET_NAME`

---

packages/litqa/src/aviary/envs/litqa/task.py
packages/litqa/tests/test_litqa_env.py
src/aviary/utils.py

- Allowing `MultipleChoiceQuestion` to hold a question ID but not put it into the `question_prompt` via a flag `prompt_without_id`
- Moved `LitQATaskDataset` to store the question ID too

`LitQATaskDataset` also storing LitQA question ID

---

packages/lfrqa/tests/test_lfrqa_env.py

Depending on where you invoke Python, this relative path was breaking

Removed relative path in `test_lfrqa_env.py`

---

.pre-commit-config.yaml
packages/gsm8k/src/aviary/envs/gsm8k/env.py
packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
packages/litqa/src/aviary/envs/litqa/env.py
packages/litqa/src/aviary/envs/litqa/task.py
packages/litqa/tests/test_litqa_env.py
pyproject.toml
src/aviary/dataset_server.py
src/aviary/env.py
src/aviary/env_client.py
src/aviary/message.py
src/aviary/render.py
src/aviary/tools/utils.py
src/aviary/utils.py
tests/test_utils.py

Updated tooling versions and configs

---

.github/workflows/tests.yml
packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
packages/lfrqa/tests/test_lfrqa_env.py

I realized this today, and it's awesome

Simplified `refurb` in CI after #196 fixed `mypy` config

---

packages/hotpotqa/src/aviary/envs/hotpotqa/env.py

The below two HotPotQA validation set questions:
- What occupation do Chris Menges and Aram Avakian share?
- Both Ralph Bakshi and Béla Gaál had what roll in film making?
- Nice to see HotPotQA questions can have typos in them, lol
Can lead to the same `Frame.info`:
```python
{'steps': 1, 'done': True, 'reward': 1.0, 'answer': 'They both served as film directors.'}
```
This PR ensures the `info` remains unique, by propagating question metadata.

Added question info to `HotPotQAEnv.export_frame`

---

README.md

Our public repos follow different badge patterns. It became more evident with the cookbook. 
Now that we are linking the platform documentation to the platform and plan to release it, the cookbook will see more traffic. This PR (together with similar ones on other repos) fixes it.

Updated repo badges

---

pyproject.toml
tests/test_envs.py
uv.lock

https://github.com/Future-House/aviary/pull/170 removed an unnecessary `async`, and missed that it's possible to remove the `pytest_asyncio.fixture` usage too. This now allows us to pull in the latest `pytest-asyncio`.

Removed unnecessary `pytest_asyncio.fixture`

---

packages/lfrqa/src/aviary/envs/lfrqa/env.py
packages/lfrqa/src/aviary/envs/lfrqa/task.py

`GradablePaperQAEnvironment` ([link](https://github.com/Future-House/aviary/blob/v0.19.0/packages/litqa/src/aviary/envs/litqa/env.py#L60)) expects a `Mapping[str, float]` for rewards, but this `str` looseness led to the `KeyError` in https://github.com/Future-House/aviary/issues/222.
So, this PR:
- Moves LFRQA's implementation to use `StrEnum`, so we can more easily align our internal implementation's keys, while still being compatible with `Mapping[str, float]`
- Fixes `LFRQAPairwiseEvalEnv` to pull the rewards from the `LFRQAQuestion.grading_rewards`, for DRY code

LFRQA using `grading_rewards` and using `Enum` for rewards implementation

---

.github/renovate.json5

Forgot to do this in https://github.com/Future-House/aviary/pull/225.

Removed `httpx` constraint from Renovate config

---

src/aviary/env.py
src/aviary/utils.py
tests/test_envs.py

Currently with an `ExceptionGroup` failure in a tool call, the emitted observation will leave agents in the dark on the failure:
```none
> Encountered exception during tool call: unhandled errors in a TaskGroup (1 sub-exception)
```
This PR fixes that, by expanding `ExceptionGroup`s:
```none
> Encountered exception during tool call: unhandled errors in a TaskGroup (1 sub-exception), where sub-exceptions are: RuntimeError('BOOM, blew out an ACL.')
```

Giving `Agent`s insight into `ExceptionGroup`s

---

pyproject.toml
src/aviary/tools/utils.py
uv.lock

Apparently the latest `litellm` minor version fixed some unexpected behavior

Pinned latest `litellm` for `tool_choice=Tool`'s `finish_reason` fix

---

README.md

This PR updates old links to tutorials in the README.
Creating Language Agents to Interact with Aviary Environments
Old link (404): https://github.com/Future-House/ldp/blob/main/docs/agent_tutorial.ipynb
New working link: https://github.com/Future-House/ldp/blob/main/tutorials/creating_a_language_agent.ipynb
Evaluate a Llama Agent on GSM8K
Old link (404): https://github.com/Future-House/ldp/blob/main/docs/gsm8k_llama_eval.ipynb
New working link: https://github.com/Future-House/ldp/blob/main/tutorials/evaluating_a_llama_agent.ipynb
Verified that the new links resolve correctly!
Note: Links to the PyPI aviary.cloning and aviary.protein_stability sub-packages will also need to be updated once they are finished being released (which appears to be on its way with this …

Update tutorial links in README.md to reflect new paths

---

packages/gsm8k/src/aviary/envs/gsm8k/env.py
packages/gsm8k/tests/test_gsm8k_env.py
packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
packages/hotpotqa/tests/test_hotpotqa_env.py
packages/lfrqa/src/aviary/envs/lfrqa/env.py
packages/lfrqa/tests/test_lfrqa_env.py
packages/litqa/src/aviary/envs/litqa/env.py
packages/litqa/tests/test_litqa_env.py
src/aviary/env.py
tests/conftest.py
tests/test_envs.py

Resolves https://github.com/Future-House/aviary/issues/165

Created async `Environment.get_id` method for unique environment ID

---

pyproject.toml
src/aviary/tools/utils.py
tests/cassettes/TestParallelism.test_dummyenv_using_empty_params.yaml
tests/cassettes/TestParallelism.test_tool_selector_from_model_name[gpt-4o-mini-2024-07-18].yaml
tests/cassettes/TestParallelism.test_tool_selector_with_external_acompletion[gpt-4o-mini-2024-07-18].yaml
uv.lock

The backstory here is:
1. https://github.com/Future-House/aviary/pull/244 pinned `litellm>=1.72.0` for improved `finish_reason` logic
2. However, last night I discovered https://github.com/BerriAI/litellm/issues/11724
So this PR:
- Restores the versions from https://github.com/Future-House/aviary/pull/244
- With the exception of the `paper-qa` edge case (as thanks to https://github.com/Future-House/paper-qa/pull/946, `paper-qa` now supports Python 3.13)
- Adds logic to check the `litellm` version at runtime, auto-selecting the appropriate validation behavior
- Refreshes all VCR cassettes using `ToolSelector`

Allowing `litellm<1.72` in `llm` extra for working VCR

---

packages/litqa/src/aviary/envs/litqa/env.py
packages/litqa/src/aviary/envs/litqa/task.py

#190 seemingly duplicated `TEvaluation` in both `env.py` and `task.py`. It only needs to be in `env.py`

Removed duplicated `TEvaluation` from LitQA

---

packages/hotpotqa/pyproject.toml
uv.lock

See https://huggingface.co/datasets/hotpotqa/hotpot_qa/discussions/8 for rationale

Downpinning `datasets` for its `trust_remote_code` deprecation

---

.github/workflows/publish.yml
.github/workflows/tests.yml

This PR also:
- Uses `steps.` references to avoid repeating the string literal `/tmp/baipp/dist` a bunch
- Fixed <https://github.com/Future-House/aviary/pull/190> forgetting to add `aviary.litqa` and `aviary.lfrqa` to `lint`'s build step

Propagating #260 to publish CI

---

packages/gsm8k/pyproject.toml
packages/hotpotqa/pyproject.toml
packages/litqa/pyproject.toml
uv.lock

I had a `uv lock --upgrade` lead to hitting `AttributeError: module 'pyarrow' has no attribute 'PyExtensionType'` from somewhere in Hugging Face `datasets`. Upon investigation, it turns out the lock resolution had downgraded to a super old `datasets` version.
https://github.com/apache/arrow/issues/47155 reveals we should just lower-pin `datasets` to a somewhat modern (Nov 2023) version, which is what this PR does.

Lower pinning `datasets` to ensure modern `pyarrow` compatibility

---

pyproject.toml
src/aviary/utils.py
tests/test_utils.py

As the title says. It was confusing for a class named MCQ to support non-MCQs. And as I've run into a few times the past couple days, we have downstream code that breaks silently if you use `MultipleChoiceQuestion` in open-answer mode (i.e. `.grade` will mark everything as wrong). 
As far as I can tell, nobody is using this code path, so I am removing it to avoid confusion. We should bring it back as a separate class eventually, with proper downstream support.

Deprecate open answer from MultipleChoiceQuestion

---

packages/notebook/src/aviary/envs/notebook/env.py

Can hit this edge case if we had a crash before/during reset and are trying to clean up after it.

Only close NBEnv state if it exists

---

src/aviary/utils.py
tests/test_utils.py

When just a fraction of the template variables were passed, `partial_format` would be an no-op. This PR fixes that, with some new unit tests.

Fixed `partial_format` working with partial variables
